### ISSUE TITLE
Run CI actions on PR

### ISSUE THREAD

**Issue by ravsii** [Boeing/config-file-validator#21]
Currently CI runs only when a commit/push is being made. 

https://github.com/Boeing/config-file-validator/blob/874028e6f2054b33c62146b5c92324d915574bde/.github/workflows/go.yml#L1-L8

Because recently the repo got somewhat active I think it's a good idea to run actions when somebody is doing a PR. This can  be achieved by:
```yaml
on:
  push:
  pull_request:
```

For discussion: Pusing to `main` is not always considered good and secure, here are 2 suggestions:

1. Remove `on:push` interely and update main only through PRs
2. (or) add a `branches` condition, so it wouldn't run CI (and waste minutes) on other (dev) branches, but still will perform actions if someone pushed directly to main, just in case.

```yaml
on:
  push:
    branches:
      - main
  pull_request:
```

Could do a PR for this if needed.
